apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: local-directory-provisioner
spec:
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  volumes:
    - projected
    - secret
    - hostPath
  allowedHostPaths:
    - pathPrefix: /mnt/ssd
